mongo:
  connectionString: mongodb://localhost:27017
  db: mymusic
  songCollection: song
  userPrefCollection: userPref
  query:
    maxLimit: 20

swagger:
  oauth:
    serverUrl: http://localhost:8090
    clientId: mymusic-client
    clientSecret: secret
security:
  oauth2:
    client:
      client-id: mymusic-api
      client-secret: secret
    resource:
      tokenInfoUri: http://localhost:8090/oauth/check_token

resource:
  rootPath: C:\Users\amber\resource\mymusic

inventory:
  rootPath: C:\Users\amber\inventory\mymusic
  defaultIconPath: C:\Users\amber\inventory\mymusic\img\music-icon.jpg

#logging.level.org.springframework.web: DEBUG
#logging.level.io.springfox: DEBUG


